version: "3"

services:
  app:
    build: ./app
    container_name: myflaskapp
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mymysqlcontainer
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro