version: "3"
services:
  app:
    image: existentialcrisismlops/myflaskapp # Use the image from Docker Hub
    platform: linux/amd64
    container_name: myflaskapp
    ports:
      - "80:80"
    depends_on:
      - db # Ensure that the database service is started before the app service
  db:
    image: existentialcrisismlops/my-mongodb-image # Use the image from Docker Hub
    container_name: my-mongodb-image
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro # Corrected volume path